### ISSUE TITLE
Support query_batch from skywind3000/ECDICT

### ISSUE THREAD

**Issue by phigrey** [HiuYanChong/node-ecdict#4]
Firstly, thank you for your work, :).
And I am using this lib for my project, and really need an interface which implements `query_batch` from  [skywind3000/ECDICT](https://github.com/skywind3000/ECDICT).

Maybe something like,
```
search_multiple('flower stand some more words').then(.....)
```
Then words don't need to be related with each other.
Thank you in advance.

**Comment by HiuYanChong** [comment]
@dorrywhale Sorry for my late reply.
Here is the [PR ](https://github.com/HiuYanChong/node-ecdict/pull/5) that includes `query_batch` feature.
